This Quick Start deploys {partner-product-name} on the AWS Cloud. This guide covers the steps necessary to deploy this Quick Start.

This guide provides instructions for deploying the MuleSoft Runtime Fabric Quick Start reference architecture on the AWS Cloud.

This Quick Start is for users who want to deploy Runtime Fabric to manage, deploy, and run Mule applications in an AWS EKS cluster.

== Runtime Fabric on Elastic Kubernetes Service (EKS)

Anypoint Runtime Fabric enables you to deploy Mule applications and API proxies to a Kubernetes cluster that you create, configure, and manage. Runtime Fabric runs as a service in EKS.

AWS customers can deploy Runtime Fabric into a new VPC and new Amazon EKS cluster, an existing VPC and a new EKS cluster, or an existing VPC and existing EKS cluster.

// For advanced information about the product, troubleshooting, or additional functionality, refer to the https://{quickstart-github-org}.github.io/{quickstart-project-name}/operational/index.html[Operational Guide^].

// For information about using this Quick Start for migrations, refer to the https://{quickstart-github-org}.github.io/{quickstart-project-name}/migration/index.html[Migration Guide^].